export { default as Home } from './Home'
export { default as Books } from './Books'
export { default as Videos } from './Videos'
export { default as VideoPage } from './Video'
export { default as Cart } from './Cart'